### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by simonbyrne** [trixi-framework/paper-2021-juliacon#22]
Trixi.jl is a very impressive piece of software, and I think the paper does a very great job of introducing and highlighting its features as a software package given the page constraints. My main comments:

1. the paper states "Trixi.jl also handles non-conservative PDE terms as in the shallow water equations”. I was bit confused by this at first as Trixi uses the conservative formulation of the SWE (https://trixi-framework.github.io/Trixi.jl/stable/reference-trixi/#Trixi.ShallowWaterEquations2D) as opposed to the so-called "vector invariant" form of the SWE. This appears to be referring to a source term that involves a spatial gradient. Could this be expressed in a slightly different way?

2. I realise such cross-language comparisons are difficult, but given the familiarity of the authors with both codebases, I would have appreciated any insight the authors might have as to the reason for the performance advantage Trixi appears to have over Fluxo (e.g. more cache-friendly memory layout, better use of SIMD or FMA operations, or utilizing different libraries?)

**Comment by ranocha** [comment]
Thank you very much for your review and your kind words, @simonbyrne! I tried to clarify the aspect of nonconservative terms in #23.

A thorough analysis of reasons for these performance differences would require a huge amount of work, basically starting from scratch in each framework and adding pieces step-by-step, monitoring the performance along the way. Thus, I don't think this is suitable for this paper. However, we will be happy to share any conjectures and insights we have on this.
- A significant difference comes from some optimizations we developed in Trixi.jl and ported to FLUXO later. These are described in [a recent preprint](https://arxiv.org/abs/2112.10517).
- Trixi.jl uses slightly different versions of computationally intensive kernels than FLUXO. I expect this to be the next big impact.
- Trixi.jl stores slightly less information in RAM and re-computes some terms, increasing performance in memory-bound parts.
- Some special functions appear to be faster in Julia, e.g., computing `sincos` instead of calling `sin` and `cos` independently in FORTRAN.

**Comment by ranocha** [comment]
@simonbyrne We merged #23 and improved the paper based on your comments above. Please let me know whether the revised version looks good to you.

**Comment by simonbyrne** [comment]
I don't think any further analysis is required, but I do think it would be helpful to include a sentence or two in the discussion of section 3 summarizing some of this. Otherwise it is a bit odd to have the benchmark experiment and results which show Trixi is faster than Fluxo, but no discussion as to why that might be the case (other than the comment "Trixi.jl owes its performance optimizations in part to the code introspection and profiling tools available in Julia").

One additional thing I found as well in section 4.1.1:

> A minor exception is due to Julia being built on top of LLVM, which does not perform the same optimizations as other C/C++/Fortran compilers. In particular, LLVM does not use fused multiply-add (FMA) instructions by default, while GCC and Intel compilers do

This isn't quite correct. This specific optimization is usually termed "FMA contraction", and is supported in the LLVM backend, but typically not enabled by default in frontends as it breaks IEEE semantics. For example, Clang has the `-ffp-contract` option, and it is also enabled by "fastmath" annotations in most languages (including Julia). In fact, the `muladd` function and `@muladd` macro are just annotations to enable this optimization locally.

**Comment by ranocha** [comment]
Thank you very much for your review, @simonbyrne. I improved the manuscript based on your comments in #24.

> Fortran itself has looser semantics, most compilers enable it by default.

In my experience, this is not only true for Fortran but also for compilers such as GCC and the Intel ones for other languages including C, e.g., [in this example](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,selection:(endColumn:2,endLineNumber:3,positionColumn:1,positionLineNumber:1,selectionStartColumn:2,selectionStartLineNumber:3,startColumn:1,startLineNumber:1),source:'double+foo(double+a,+double+b,+double+c)+%7B%0A++++return+a+*+b+%2B+c%3B%0A%7D%0A'),l:'5',n:'0',o:'C%2B%2B+source+%231',t:'0')),k:49.73108421953307,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:g111,filters:(b:'0',binary:'1',commentOnly:'0',demangle:'0',directives:'0',execute:'1',intel:'0',libraryCode:'0',trim:'1'),fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,libs:!(),options:'-O2+-march%3Dcore-avx2',selection:(endColumn:12,endLineNumber:3,positionColumn:1,positionLineNumber:1,selectionStartColumn:12,selectionStartLineNumber:3,startColumn:1,startLineNumber:1),source:1),l:'5',n:'0',o:'x86-64+gcc+11.1+(Editor+%231,+Compiler+%231)+C%2B%2B',t:'0')),k:50.26891578046694,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4).

**Comment by ranocha** [comment]
Thanks again for your constructive criticism, @simonbyrne. We merged PR #24 improving the manuscript based on your comments. Please let me know whether everything looks good to you.

**Comment by ranocha** [comment]
@simonbyrne Can we close this issue or is there anything else you would like to see changed?

**Comment by simonbyrne** [comment]
No, this can be closed.

Thank you for the paper, it was a great read.

**Comment by ranocha** [comment]
Well, thank you for your nice review and your help in improving our manuscript.
